// Shared, environment-agnostic content parsing (usable from Next.js server
// components AND plain node/tsx ingestion scripts).

/**
 * Parses a canonical text.<lang>.md file into sections.
 * Heading format (generated by the extraction pipeline):
 *   ## §I — Section title       (Discourse-style)
 *   ## ¶12                       (Monadology-style, no title)
 */
export interface ParsedSection {
  label: string;
  title: string | null;
  anchor: string;
  paragraphs: string[];
}

const headingPattern = /^##\s+§?¶?([^—–-]+?)(?:\s*[—–-]\s*(.*))?$/;

export function parseWorkText(md: string): ParsedSection[] {
  const sections: ParsedSection[] = [];
  let current: ParsedSection | null = null;

  for (const rawLine of md.split('\n')) {
    const line = rawLine.trim();
    const m = headingPattern.exec(line);
    if (m) {
      current = {
        label: m[1].trim(),
        title: m[2]?.trim() ?? null,
        anchor: m[1].trim().toLowerCase().replace(/[^a-z0-9]+/g, ''),
        paragraphs: [],
      };
      sections.push(current);
      continue;
    }
    if (line === '' || current === null) continue;
    current.paragraphs.push(line);
  }
  return sections;
}
